### ISSUE TITLE
Find a JavaScript library for machine learning

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-code-reviews-browser#113]
This is basically just doing research.

**Comment by rolfbjarne** [comment]
There's tensorflow.js: https://www.tensorflow.org/js

Test site: https://storage.googleapis.com/tfjs-models/demos/toxicity/index.html

**Comment by rolfbjarne** [comment]
It seems quite slow though (4-5s for each request in Safari, about 1s in Chrome)

**Comment by jonathanpeppers** [comment]
I added the 4th row on their example, and it seems OK with my comment ([their dataset](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data)):

![image](https://user-images.githubusercontent.com/840039/169607006-985da9a5-7228-4ae3-a8c2-dfb91837c87b.png)

It definitely seems like we have to train our own model, to get what we want...

**Comment by jonathanpeppers** [comment]
We're using https://github.com/microsoft/onnxruntime with an ML.NET exported to onnx format.

We can close this now.
