### ISSUE TITLE
Comment is "too brief" - Minimum should be 9 characters

### ISSUE THREAD

**Issue by RussKie** [jonathanpeppers/inclusive-code-reviews-browser#119]
![image](https://user-images.githubusercontent.com/4403806/174512093-f87480f8-5921-470f-994a-80e0e2d3a21c.png)

I often do thank contributors once a PR is merged. I don't see much value in turning the thanking process into a "war and peace" style. 
In general, I'm wondering what behaviour we're trying to prevent with this check.

**Comment by RussKie** [comment]
Here's another one:
![image](https://user-images.githubusercontent.com/4403806/174512960-a6ed2741-42c0-4318-aebf-cb26075b6dcf.png)

**Comment by jonathanpeppers** [comment]
The first one, I would say "Thank you" *is* too brief. "Thank you for the merge!" is definitely better. We just have a warning on less than 10 characters.

Let's keep this open for the second screenshot though. Thanks!

**Comment by RussKie** [comment]
> The first one, I would say "Thank you" _is_ too brief. "Thank you for the merge!" is definitely better

I thank contributors after I merge their PR. "Thank you for your contribution" is long and isn't adding much value, it's still a _thank you_.

**Comment by jonathanpeppers** [comment]
I would still say "Thank you for your contribution!" is more inclusive and better than "Thank you".

"Thank you for this!" would also be OK.

**Comment by jonathanpeppers** [comment]
We discussed this some more, and I think we're going to lower the minimum to 9 characters. So a phrase like `Thank you` is exactly nine characters and should be fine.

Marking this "up-for-grabs", add a test that checks `Thank you` is OK. Thanks!
