### ISSUE TITLE
Report sentence to improve heuristics

### ISSUE THREAD

**Issue by manjumegh** [jonathanpeppers/inclusive-code-reviews-browser#154]
The following word or sentence is acceptable:
this is not how we implement, take a look at my code.
we don't follow this codestyle, 
this should immediatly be deleted
Don't wait for my review comments
i have already mentioned this multiple times. 
Again, i am mentioning, this should be rephrased like.
why is this blank line here?
why is this space after comma?
can't you rename it something better,
This is so confusing.

Additional info:

Above all comments are classified as acceptable, 
|

 

* isPartialValidation: false
* isPicky: false
* isPunctuationError: false
* isSpellingError: false
* isStyleError: true
* language: en-US (English (US))

**Comment by jonathanpeppers** [comment]
Three of these actually seem like they should be flagged:
```
i have already mentioned this multiple times.
this should immediately be deleted
This is so confusing.
```
Maybe the rest are OK, though?

I'll fix these three for now, @rachelkang do you have an opinion if the others are bad?

**Comment by jonathanpeppers** [comment]
I think the remaining ones above are borderline, so I think we can close this for now. Let me know if there is a specific one we should underline besides these:

![image](https://user-images.githubusercontent.com/840039/193352243-ab310815-9138-4cee-bcc2-2d80569ad7ff.png)

The "Again, I am mentioning" maybe we could add some phrases to the model like:
```
I can't believe I have to mention this again
```
