### ISSUE TITLE
Improving multiword expression support

### ISSUE THREAD

**Issue by weng5e** [jonathanpeppers/inclusive-code-reviews-browser#172]
It seems like the word sentiment analysis is focusing on a single word without taking into consideration for mutiword expressions. It would be better if it can recognize multiword expressions and take those words as a whole for analysis.

Example:
English is not my `native` language. 

The word `native` is tagged, while the expression `native language` should probably be considered as a whole.

![image](https://user-images.githubusercontent.com/22308724/202537520-11aad39f-66e1-4485-afe7-a332b95aaad0.png)

**Comment by jonathanpeppers** [comment]
We did ask the Microsoft naming committee about the word "native", and they came back saying it's OK.

"My native language is English", "I am a native Kentuckian", or "I am a New England native", for example. @rachelkang did you have any other thoughts on this one?
