### ISSUE TITLE
Report sentence to improve heuristics

### ISSUE THREAD

**Issue by AndreyTretyak** [jonathanpeppers/inclusive-code-reviews-browser#181]
The following word or sentence is acceptable:

    Hi Chuck,

Additional info:

* Description: This phrase could be considered negative. Would you like to rephrase?
* Context phrase: |Hi Chuck,
|

Thanks for me...
* isPartialValidation: false
* isPicky: false
* isPunctuationError: false
* isSpellingError: false
* isStyleError: true
* language: en-US (English (US))

**Comment by jonathanpeppers** [comment]
I could reproduce just using our ML model, I suspect "Chuck" is similar to various other profane words and that caused this.
