### ISSUE TITLE
"You are generous with your time" flagged for negative sentiment

### ISSUE THREAD

**Issue by alisonlomaka** [jonathanpeppers/inclusive-code-reviews-browser#288]
<img width="266" alt="image" src="https://github.com/jonathanpeppers/inclusive-code-reviews-browser/assets/98775110/e9be9d55-c9c4-4db0-a6ef-ad35b24c62f6">

Not obvious to me how this is negative, seems like a bug?

**Comment by jonathanpeppers** [comment]
Thanks for reporting! For next time, you can use this button to quickly report more of these:

![image](https://github.com/jonathanpeppers/inclusive-code-reviews-browser/assets/840039/c4f7a386-0311-4a17-86f7-21121ac1735d)

We are kind of trying to "croudsource" to find more.

Machine learning can be odd, but I bet the pattern the model detects is "generate" as we have a couple bad comments using that:

https://github.com/jonathanpeppers/inclusive-code-reviews-ml/blob/31c2d53c18cff32ea8efc40d9323a91ba5858ed7/comments/classified.csv#L47-L49

**Comment by alisonlomaka** [comment]
[0]     Alison Lomaka reacted to your message:
________________________________

**Comment by alisonlomaka** [comment]
[like]  Alison Lomaka reacted to your message:
________________________________
