### ISSUE TITLE
Investigate effects of punctuation, spaces, and line breaks

### ISSUE THREAD

**Issue by rachelkang** [jonathanpeppers/inclusive-code-reviews-browser#34]
More words than necessary are getting flagged, when just a substring of the text needs to be.

For example, in the following case, only the last word after the period is flagged/underlined:
hi
my name
is
Rachel. ugh.

whereas here, everything from this line onwards is flagged/underlined:
hi
my name
is
Rachel ugh

**Comment by rmarinho** [comment]
There are some rules on the settings page that relate with this..

**Comment by rachelkang** [comment]
Hmm AFAICT it seems to not help with cases like the sample I shared. But we should definitely investigate further!

**Comment by jonathanpeppers** [comment]
It looks like Azure Text Analytics is dividing this into sentences:

One sentence:

![image](https://user-images.githubusercontent.com/840039/141527096-40bc7791-be4c-4f35-9fcd-daae7c132b63.png)

Then this is another sentence:

![image](https://user-images.githubusercontent.com/840039/141527066-1af2bdb5-b5eb-4bfe-8369-79df5c3d9219.png)

**Comment by jonathanpeppers** [comment]
Using the 2.0.0 model, it seems like everything is OK now:

![image](https://user-images.githubusercontent.com/840039/184451493-6a986a62-ef00-4962-9c7f-6a9f36835a04.png)
