### ISSUE TITLE
Report sentence to improve heuristics

### ISSUE THREAD

**Issue by debonte** [jonathanpeppers/inclusive-code-reviews-browser#348]
The following word or sentence is acceptable:

    hit

Additional info:

* Description: This word has a negative connotation. Did you want to use a different word?
* Context phrase: ...is non-zero. I |hit| an issue yeste...
* isPartialValidation: false
* isPicky: false
* isPunctuationError: false
* isSpellingError: false
* isStyleError: false
* language: en-US (English (US))

**Comment by jonathanpeppers** [comment]
This one we suggest one of:

https://github.com/jonathanpeppers/inclusive-code-reviews-browser/blob/2567b51ee0a8d0b810577d7731afbc6fe46697ad/src-packed/suggestions.js#L69

This originally came from a contributor, that generally `click` is probably better than `hit`: https://github.com/jonathanpeppers/inclusive-code-reviews-browser/commit/b1c734c6268a3b5c865d190ff588c98edce2ff32

To be honest, I'm on the fence on this one. But the suggestions it offers do seem to be better?

**Comment by debonte** [comment]
I don't think anyone would interpret the word "hit" in "I hit an issue yesterday..." as violent or offensive. Is the analyzer currently just looking for the presence of certain words and not able to determine whether the words are used in a concerning way?

For example, "I'm going to hit you," would be concerning. Whereas, "I think you really hit a home run with this change!" would not be.

**Comment by jonathanpeppers** [comment]
We have two features: list of words to replace and only sentiment analysis uses AI.

“Hit” is on our list to replace no matter what. I could see someone not liking that word in general, but I’ll look for some guidance somewhere about it.

**Comment by jonathanpeppers** [comment]
What I'm finding is that it's generally recommended to say "click this button" instead of "hit this button". It might be more about non-English speakers.

I found something on Reddit:

https://www.reddit.com/r/instructionaldesign/comments/14a6ygq/comment/jobajsb/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

I tried ChatGPT myself and it says:

> Terms like "click", "select", or "choose" are clear and widely understood in the context of digital interfaces, making them inclusive in terms of understandability. However, "hit" might be considered informal and less precise, potentially leading to confusion for non-native English speakers or those unfamiliar with colloquial expressions

So thinking about "hit an issue", it does seem like "run into an issue" might be better?

**Comment by jonathanpeppers** [comment]
Closing for now, unless someone has a stronger opinion. Thanks!
